; Windows shell integration for the NSIS distribution. SHCTX follows the
; installer's current-user/per-machine choice, so registration and cleanup
; always happen in the same registry hive.

; Keep this list deliberately limited to formats that are conventionally
; plain text or source code. The generic `text` association below remains a
; useful fallback, while these explicit entries also cover extensions whose
; PerceivedType is not registered as text on a particular Windows install.
!macro REGISTER_GLYPHRA_TEXT_EXTENSION EXT
  WriteRegStr SHCTX "Software\Classes\SystemFileAssociations\.${EXT}\shell\Glyphra.OpenFile" "" "Open with Glyphra"
  WriteRegStr SHCTX "Software\Classes\SystemFileAssociations\.${EXT}\shell\Glyphra.OpenFile" "Icon" "$INSTDIR\${MAINBINARYNAME}.exe,0"
  WriteRegStr SHCTX "Software\Classes\SystemFileAssociations\.${EXT}\shell\Glyphra.OpenFile\command" "" '$"$INSTDIR\${MAINBINARYNAME}.exe$" $"%1$"'
!macroend

!macro UNREGISTER_GLYPHRA_TEXT_EXTENSION EXT
  DeleteRegKey SHCTX "Software\Classes\SystemFileAssociations\.${EXT}\shell\Glyphra.OpenFile"
!macroend

!macro NSIS_HOOK_POSTINSTALL
  ; Explorer folder context menu.
  WriteRegStr SHCTX "Software\Classes\Directory\shell\Glyphra" "" "Open Folder with Glyphra"
  WriteRegStr SHCTX "Software\Classes\Directory\shell\Glyphra" "Icon" "$INSTDIR\${MAINBINARYNAME}.exe,0"
  WriteRegStr SHCTX "Software\Classes\Directory\shell\Glyphra\command" "" '$"$INSTDIR\${MAINBINARYNAME}.exe$" $"%1$"'

  ; Explorer background context menu passes the directory as %V.
  WriteRegStr SHCTX "Software\Classes\Directory\Background\shell\Glyphra" "" "Open Folder with Glyphra"
  WriteRegStr SHCTX "Software\Classes\Directory\Background\shell\Glyphra" "Icon" "$INSTDIR\${MAINBINARYNAME}.exe,0"
  WriteRegStr SHCTX "Software\Classes\Directory\Background\shell\Glyphra\command" "" '$"$INSTDIR\${MAINBINARYNAME}.exe$" $"%V$"'

  ; Text files get a dedicated Explorer action without taking over the
  ; user's default file associations.
  WriteRegStr SHCTX "Software\Classes\SystemFileAssociations\text\shell\Glyphra.OpenFile" "" "Open with Glyphra"
  WriteRegStr SHCTX "Software\Classes\SystemFileAssociations\text\shell\Glyphra.OpenFile" "Icon" "$INSTDIR\${MAINBINARYNAME}.exe,0"
  WriteRegStr SHCTX "Software\Classes\SystemFileAssociations\text\shell\Glyphra.OpenFile\command" "" '$"$INSTDIR\${MAINBINARYNAME}.exe$" $"%1$"'

  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "txt"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "md"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "markdown"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "rst"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "adoc"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "log"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "csv"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "tsv"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "json"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "jsonc"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "yaml"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "yml"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "toml"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "xml"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "ini"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "cfg"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "conf"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "env"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "properties"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "c"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "cc"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "cpp"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "cxx"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "h"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "hh"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "hpp"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "hxx"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "cs"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "css"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "scss"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "sass"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "less"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "go"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "java"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "js"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "jsx"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "mjs"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "cjs"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "ts"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "tsx"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "vue"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "svelte"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "html"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "htm"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "php"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "py"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "pyw"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "rb"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "rs"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "swift"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "kt"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "kts"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "lua"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "r"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "sql"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "graphql"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "gql"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "sh"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "bash"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "zsh"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "fish"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "ps1"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "psm1"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "bat"
  !insertmacro REGISTER_GLYPHRA_TEXT_EXTENSION "cmd"

  ; Also advertise Glyphra in Windows' Open with picker for common text formats.
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe" "FriendlyAppName" "Glyphra"
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\DefaultIcon" "" "$INSTDIR\${MAINBINARYNAME}.exe,0"
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\shell\open" "FriendlyAppName" "Open with Glyphra"
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\shell\open\command" "" '$"$INSTDIR\${MAINBINARYNAME}.exe$" $"%1$"'
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".txt" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".md" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".markdown" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".log" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".json" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".jsonc" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".yaml" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".yml" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".toml" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".xml" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".csv" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".ini" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".cfg" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".conf" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".env" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".properties" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".rst" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".adoc" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".csv" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".tsv" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".c" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".cc" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".cpp" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".cxx" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".h" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".hh" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".hpp" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".hxx" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".cs" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".css" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".scss" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".sass" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".less" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".go" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".java" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".js" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".jsx" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".mjs" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".cjs" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".ts" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".tsx" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".vue" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".svelte" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".html" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".htm" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".php" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".py" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".pyw" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".rb" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".rs" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".swift" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".kt" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".kts" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".lua" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".r" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".sql" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".graphql" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".gql" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".sh" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".bash" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".zsh" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".fish" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".ps1" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".psm1" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".bat" ""
  WriteRegStr SHCTX "Software\Classes\Applications\Glyphra.exe\SupportedTypes" ".cmd" ""

  ; Makes Glyphra discoverable through ShellExecute / Win+R without mutating PATH.
  WriteRegStr SHCTX "Software\Microsoft\Windows\CurrentVersion\App Paths\Glyphra.exe" "" "$INSTDIR\${MAINBINARYNAME}.exe"
  WriteRegStr SHCTX "Software\Microsoft\Windows\CurrentVersion\App Paths\Glyphra.exe" "Path" "$INSTDIR"

  System::Call 'shell32::SHChangeNotify(i 0x08000000, i 0, p 0, p 0)'
!macroend

; Run only after Tauri has confirmed the app can be removed, so a cancelled
; uninstall does not leave Explorer registration half-removed.
!macro NSIS_HOOK_POSTUNINSTALL
  DeleteRegKey SHCTX "Software\Classes\Directory\shell\Glyphra"
  DeleteRegKey SHCTX "Software\Classes\Directory\Background\shell\Glyphra"
  DeleteRegKey SHCTX "Software\Classes\SystemFileAssociations\text\shell\Glyphra.OpenFile"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "txt"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "md"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "markdown"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "rst"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "adoc"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "log"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "csv"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "tsv"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "json"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "jsonc"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "yaml"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "yml"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "toml"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "xml"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "ini"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "cfg"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "conf"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "env"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "properties"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "c"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "cc"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "cpp"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "cxx"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "h"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "hh"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "hpp"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "hxx"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "cs"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "css"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "scss"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "sass"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "less"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "go"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "java"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "js"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "jsx"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "mjs"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "cjs"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "ts"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "tsx"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "vue"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "svelte"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "html"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "htm"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "php"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "py"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "pyw"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "rb"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "rs"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "swift"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "kt"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "kts"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "lua"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "r"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "sql"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "graphql"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "gql"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "sh"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "bash"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "zsh"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "fish"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "ps1"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "psm1"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "bat"
  !insertmacro UNREGISTER_GLYPHRA_TEXT_EXTENSION "cmd"
  DeleteRegKey SHCTX "Software\Classes\Applications\Glyphra.exe"
  DeleteRegKey SHCTX "Software\Microsoft\Windows\CurrentVersion\App Paths\Glyphra.exe"
  System::Call 'shell32::SHChangeNotify(i 0x08000000, i 0, p 0, p 0)'
!macroend
